# feeder
feeder: feeders.feeder.Feeder
dataloader:
  data_path: ../Datasets/UCF-101/
  label_path: ../Datasets/UCF-101/ucf101_annotations.yaml
  debug: False
  preprocessed: True
  skel_path: ./data/UCF-101/skeleton/
  flow_path: ./data/UCF-101/flow/


# model
model: model.msg3d.Model
model_args:
  num_class: 101
  num_point: 17 # if you change num points, must change graph option below!!
  num_person: 2
  num_gcn_scales: 8
  num_g3d_scales: 8
  graph: graph.yolo_pose.AdjMatrixGraph
#ignore_weights: ["data_bn.weight", "data_bn.bias", "data_bn.running_mean", "data_bn.running_var"]
ignore_weights: []


# test
phase: test
device: cpu
test_batch_size: 64
#weights: ./pretrained_models/kinetics_joint.pt
weights: 

work_dir: ./eval/kinetics/joint/
save_score: True