# Feeder
feeder: feeders.ntu_rgb_d.Feeder
feeder_args:
  data_paths:
    CSet: ./data/ntu120/aligned_data/poseoff/RAFT/ntu120_CSet-poseoff_RAFT_D3_aligned.npz
    CSub: ./data/ntu120/aligned_data/poseoff/RAFT/ntu120_CSub-poseoff_RAFT_D3_aligned.npz
  label_path: ./data/ntu120/statistics/ntu_rgbd120-annotations.yaml
  p_interval: [0.5, 1]
  random_choose: True
  random_shift: True
  window_size: 300
  random_move: True
  random_rot: True
  average_flow: True # model_args.flow_channels = 2
  absolute_flow: False
    # window_mean:  # model_args.flow_channels = 1 if true, else 25 (for 5x5 window)
  no_flow: False
  no_Z: False

extractor:
  preprocessed: True
  pose:
    weights: pretrained_models/yolo11x-pose.pt
  flow:
    weights: pretrained_models/raft_large.pt
    imsize: [1080,1920]
    minibatch_size: 3 # can be up to 16 for imsize: [240,320]
  poseoff:
    window_size: 5
    threshold: 0.05
    loop: False
    norm: False
    match_pose: False
    ntu: True
    dilation: 3

# model
model: models.msg3d.TEST_MODEL
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 2
  num_g3d_scales: 3
  graph: graph.ntu_rgb_d.Graph
  pose_channels: 3
  flow_channels: 2
  cnn: False
ignore_weights: []
phase: train

# Optimiser
optimiser: torch.optim.SGD
optim_params:
  lr: 0.05
  momentum: 0.9
  weight_decay: 0.0005
  nesterov: True

# Scheduler
scheduler: torch.optim.lr_scheduler.MultiStepLR
scheduler_params:
  milestones: [30, 50]
  gamma: 0.1

# training
training_function: training.train_msg3d.train_network
testing_function: training.eval_msg3d.eval_network
num_epoch: 60
device: 0
batch_size: 128
forward_batch_size: 128
test_batch_size: 128
half: False

checkpoint_freq: 10 # how often to save the model and training state
save_location: ./results/msg3d/ntu120/ # where to save the checkpoints
