# dataloader
dataloader:
  data_path: ../Datasets/UCF-101/
  label_path: ../Datasets/UCF-101/ucf101_annotations.yaml
  skel_path: ./data/UCF-101/skeleton/
  flow_path: ./data/UCF-101/flow/

#ignore_weights: ["data_bn.weight", "data_bn.bias", "data_bn.running_mean", "data_bn.running_var"]
ignore_weights: []

pose: 
  weights: pretrained_models/yolo11x-pose.pt

flow:
  weights: pretrained_models/raft_large.pt
  minibatch_size: 16

device: 0

# If the following parameter is provided, then the array given by 
# the bash script is the indexes for elements in here
# unfinished: [PlayingSitar, PlayingDhol, Billiards, PlayingDaf, RockClimbingIndoor, JumpRope, Punch, Drumming, IceDancing]