# Feeder
feeder: feeders.ucf101.Feeder
feeder_args:
  data_paths: 
    1: ./data/UCF-101/flowpose/ucf101_01.npz
    2: ./data/UCF-101/flowpose/ucf101_02.npz
    3: ./data/UCF-101/flowpose/ucf101_03.npz
  label_path: ../Datasets/UCF-101/ucf101_annotations.yaml
  p_interval: [0.5, 1]
  random_shift: True
  random_choose: True
  window_size: 64
  random_move: True
  random_rot: True
  average_flow: False
  absolute_flow: 
    window_mean: True # model_args.flow_channels = 1 if true, else 25 (for 5x5 window)
  no_flow: False

extractor:
  data_paths:
    rgb_path: ../Datasets/UCF-101/
    pose_path: ./data/UCF-101/pose/
    flow_path: ./data/UCF-101/flow/
    flowpose_path: ./data/UCF-101/flowpose/
  preprocessed: True
  pose: 
    weights: pretrained_models/yolo11x-pose.pt
  flow:
    weights: pretrained_models/raft_large.pt
    imsize: [240,320]
    minibatch_size: 16
  flowpose:
    window_size: 5
    threshold: 0.05
    loop: False
    
# model
model: model.infogcn2.sode.SODE
model_args:
  num_class: 101
  num_point: 17
  num_person: 2
  graph: graph.yolo_pose.Graph
  pose_channels: 3
  flow_channels: 1 
  embed_channels: 64
  num_head: 3
  ode_method: euler
  depth: 4
  device: 0
  T: 64 # Maximum sequence length
  n_step: 3 # Number of ODE solver steps
  SAGC_proj: True # Using self-attention graph convolution, (GCN if False)
  num_cls: 10 # Number of classification heads used
  n_sample: 1
  backbone: transformer
  cnn: False
ignore_weights: []
phase: train
# weights: ./pretrained_models/kinetics_joint.pt

optim:
  base_lr: 0.1
  nesterov: True
  weight_decay: 0.0003
  step: [50, 60]
  gamma: 0.1
  # weight_decay: 0.0005
  # step: [45,55,80]
  # gamma: 0.90
lambda_1: 1 # CLS loss (1 from paper)
lambda_2: 0.1 # Pred/recon loss (1e-1 from paper)
lambda_3: 0.001 # Feature loss (1e-3 from paper)
lambda_4: 0.0
lambda_5: 0.0
  

# training
num_epoch: 70
device: 0
batch_size: 256
forward_batch_size: 128
test_batch_size: 256
half: False

checkpoint_freq: 10 # how often to save the model and training state
save_location: ./results/ucf101/ # where to save the checkpoints