# Feeder
feeder: feeders.ucf101.Feeder
feeder_args:
  data_paths:
    1: ./data/ucf101/aligned_data/ucf101_01_D1.npz
    2: ./data/ucf101/aligned_data/ucf101_02_D1.npz
    3: ./data/ucf101/aligned_data/ucf101_03_D1.npz
  label_path: ./data/ucf101/statistics/ucf101_annotations.yaml
  p_interval: [0.5, 1]
  random_choose: True
  random_shift: True
  window_size: 300
  random_move: True
  random_rot: True
  average_flow: False # model_args.flow_channels = 2
  absolute_flow:
    window_mean: True # model_args.flow_channels = 1 if true, else 25 (for 5x5 window)
  no_flow: False

extractor:
  data_paths:
    rgb_path: ../Datasets/UCF-101/
    pose_path: ./data/ucf101/pose/
    flow_path: ./data/ucf101/flow/
    poseoff_path: ./data/ucf101/poseoff/
  pose:
    weights: pretrained_models/yolo11x-pose.pt
  flow:
    weights: pretrained_models/raft_large.pt
    imsize: [240,320]
    minibatch_size: 16
  poseoff:
    window_size: 5
    threshold: 0.05
    loop: False
    norm: False
    match_pose: False
    ntu: False
    dilation: 3

# model
model: models.msg3d.TEST_MODEL
model_args:
  num_class: 101
  num_point: 17
  num_person: 2
  num_gcn_scales: 2
  num_g3d_scales: 3
  graph: graph.yolo_pose.Graph
  pose_channels: 3
  flow_channels: 1
  cnn: False
ignore_weights: []
phase: train

# Optimiser
optimiser: torch.optim.SGD
optim_params:
  lr: 0.05
  momentum: 0.9
  weight_decay: 0.0005
  nesterov: True

# Scheduler
scheduler: torch.optim.lr_scheduler.MultiStepLR
scheduler_params:
  milestones: [30, 50]
  gamma: 0.1

# training
training_function: training.train_msg3d.train_network
testing_function: training.eval_msg3d.eval_network
num_epoch: 50
device: 0
batch_size: 128
forward_batch_size: 128
test_batch_size: 128
half: False

checkpoint_freq: 10 # how often to save the model and training state
save_location: ./results/msg3d/ucf101/ # where to save the checkpoints
